[package]
cairo-version = "=2.10.1"
name = "tamagotchi"
version = "0.1.0"
edition = "2023_11"

[cairo]
sierra-replace-ids = true

[scripts]
sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate --account-address $DEPLOYER_ACCOUNT_ADDRESS --private-key $DEPLOYER_PRIVATE_KEY"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.1" }
achievement = { git = "https://github.com/cartridge-gg/arcade", tag = "v1.6.0-alpha.1" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "achievement::events::index::e_TrophyCreation", 
    "achievement::events::index::e_TrophyProgression", 
]

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0-alpha.1" }

[profile.sepolia]
[profile.slot]
