# The World address to index.
world_address = "0x0605715b84ddacd1997810c948ad07867b69e664012559f0dd4b515034ce6cd9"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_9"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[sql]
historical = ["tamagotchi-TrophyProgression"] 