# The World address to index.
world_address = "0x01e87c289aacc73a6b5ac33688097cc13de58b7b5da2168573bd610e859fd9a9"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_8"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[sql]
historical = ["tamagotchi-TrophyProgression"] 