# The World address to index.
world_address = "0x03e658bb42a3655d176a67648793c01f4b4fa4a14c1bebf770c151ec0adc5a1b"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_9"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[sql]
historical = ["tamagotchi-TrophyProgression"] 