# The World address to index.
world_address = "0x020f246f511e93764ee7f174f5ece78c9dfafe1d537bbf05c48c59134b5de4f3"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_8"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[sql]
historical = ["tamagotchi-TrophyProgression"] 